### ISSUE TITLE
Edge Case: mod_md fails startup when finding unexpected store file

### ISSUE THREAD

**Issue by SneakyWhoami** [icing/mod_md#218] opened 2020-06-15 13:50 UTC
First my error log:

```
$ cat /var/log/apache2/error.log
[Tue Jun 16 00:00:11.811774 2020] [md:error] [pid 941828:tid 139784433171520] (20)Not a directory: loading mds
[Tue Jun 16 00:00:11.811818 2020] [md:error] [pid 941828:tid 139784433171520] (20)Not a directory: AH10073: synching 9 mds to registry
[Tue Jun 16 00:00:11.811823 2020] [:emerg] [pid 941828:tid 139784433171520] AH00020: Configuration Failed, exiting
[Tue Jun 16 01:31:07.830412 2020] [md:error] [pid 1059217:tid 140257231723584] (20)Not a directory: loading mds
[Tue Jun 16 01:31:07.830460 2020] [md:error] [pid 1059217:tid 140257231723584] (20)Not a directory: AH10073: synching 9 mds to registry
AH00016: Configuration Failed
```

What happened is this:
I run a unifi controller and I have a script to copy the letsencrypt certificate into the unifi controller's weird pkcs12 or whatever keystore. The script (there are several out there like this) checks that the certificate hasn't change using the program `md5sum`. The checksum file gets put into the md root (eg on ubuntu `/etc/apache2/md`). When the apache is restarted, it crashes because `privkey.pem.md5` is not a directory.

I won't be surprised if I'm the only person on the planet with this configuration right now, to be honest, but that's what I think happened. I deleted the checksum file and changed its location in the third party script so that it no longer generates in the `md` directory, and everything works again.

This means that if someone, for some reason somehow drops a random file in the `md` directory, it will prevent apache from starting.

By the way cheers, this mod is super cool!

**Comment by icing** [comment] 2020-06-15 13:56
Thanks for the positive feedback! I guess I have to add a test case for such a case and see if I can reproduce it. If not, I'd need your help to analyse this further.

**Comment by icing** [comment] 2020-06-15 15:27
Hmm, I added a test case where I create a file named `privkey.pem.md5` in the root store dir, in `domains` and in `staging` and all seems to work.

Could you try reproducing this with `LogLevel md:trace1` and send me/attach the parts of the error.log startup? (make sure it contains no info you do not want public). Thanks!

**Comment by SneakyWhoami** [comment] 2020-06-16 09:41
Apologies, it seems I specified the wrong directory in my report. Here is what I can execute to cause the effect:
`root@yellow:/etc/apache2/md/domains# touch poo`
(and then restart apache)

Error log follows, anyway:
[error.log](https://github.com/icing/mod_md/files/4785737/error.log)

**Comment by icing** [comment] 2020-06-16 16:00
Thanks! I see in the log that you seem to be using an older version. Which one do you have?

**Comment by SneakyWhoami** [comment] 2020-06-17 07:28
2.4.41-4ubuntu3 (from canonical's universe repository for their current release, "focal fossa")

**Comment by icing** [comment] 2021-01-05 12:09
I tried to reproduce this in the test suite, but failed. Have we any new updates on this? Otherwise I would close this as not reproducible.

**Comment by icing** [comment] 2021-01-11 14:39
Unable to reproduce.

**Closed by icing** 2021-01-11 14:39 UTC
